import { test as setup } from "@playwright/test";
import fs from "fs";
import path from "path";
import { USERS, PASSWORD } from "./fixtures/seed-data.mjs";

// Arch A2 / Step 1 — generate a saved login session (storageState) per seeded
// role by driving the real /login form. Steps 2+ (route-crawl, flows, isolation)
// reuse these via `test.use({ storageState })`. The .auth/ dir is gitignored —
// it holds live session JWTs and is regenerated by `npm run test:e2e:setup`.
//
// Prereq: `npm run seed:e2e` (creates the credentials) + a running dev server.

const AUTH_DIR = path.join(process.cwd(), "tests", "e2e", ".auth");

for (const u of USERS) {
  setup(`authenticate ${u.key} (${u.role})`, async ({ page }) => {
    fs.mkdirSync(AUTH_DIR, { recursive: true });

    await page.goto("/login");
    await page.fill('input[name="email"]', u.email);
    await page.fill('input[name="password"]', PASSWORD);
    await Promise.all([
      page.waitForURL((url) => !url.pathname.startsWith("/login"), { timeout: 30_000 }),
      page.click('button[type="submit"]'),
    ]);

    await page.context().storageState({ path: path.join(AUTH_DIR, `${u.key}.json`) });
  });
}
