"use client";

import { ArrowRight, CheckCircle2, Nfc, Bell, Video, Wifi } from "lucide-react";
import { useLenis } from "../SmoothScrollProvider";
import type { FeaturePanelData, MockupVariant } from "../data";

/* ── Coded UI mockups (no images — real components with fake data) ─────── */

function MockupFrame({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-slate-700/60 bg-slate-900 shadow-2xl shadow-slate-300/60 dark:shadow-black/40 overflow-hidden">
      <div className="px-4 py-2.5 bg-slate-800/80 border-b border-slate-700/60 flex items-center gap-2">
        <div className="flex gap-1.5" aria-hidden="true">
          <div className="w-2.5 h-2.5 rounded-full bg-rose-400/80" />
          <div className="w-2.5 h-2.5 rounded-full bg-amber-400/80" />
          <div className="w-2.5 h-2.5 rounded-full bg-emerald-400/80" />
        </div>
        <span className="text-[11px] text-slate-400 font-mono ml-2">{title}</span>
      </div>
      <div className="p-4 sm:p-5">{children}</div>
    </div>
  );
}

const Chip = ({ label, cls }: { label: string; cls: string }) => (
  <span className={`inline-flex px-2 py-0.5 rounded-md text-[10px] font-bold ${cls}`}>{label}</span>
);

function TimetableMockup() {
  const days = ["Mon", "Tue", "Wed", "Thu", "Fri"];
  const cells = [
    ["CS101", "", "MA204", "", "PH110"],
    ["", "CS101", "", "LAB-2", ""],
    ["EN101", "", "CS233", "", "MA204"],
    ["", "LAB-1", "", "CS101", ""],
  ];
  const colors = ["bg-violet-500/80", "bg-cyan-500/70", "bg-emerald-500/70", "bg-amber-500/70"];
  return (
    <MockupFrame title="aura.edu/timetable">
      <div className="grid grid-cols-5 gap-1.5 mb-1.5">
        {days.map(d => (
          <div key={d} className="text-center text-[10px] font-bold text-slate-500 uppercase">{d}</div>
        ))}
      </div>
      {cells.map((row, r) => (
        <div key={r} className="grid grid-cols-5 gap-1.5 mb-1.5">
          {row.map((cell, c) => (
            <div key={c}
              className={`h-9 rounded-lg flex items-center justify-center text-[9px] font-bold text-white ${
                cell ? colors[(r + c) % colors.length] : "bg-slate-800/80"
              }`}>
              {cell}
            </div>
          ))}
        </div>
      ))}
      <div className="mt-3 flex items-center justify-between text-[10px]">
        <Chip label="✓ 0 conflicts" cls="bg-emerald-500/15 text-emerald-400 border border-emerald-500/25" />
        <span className="text-slate-500">Generated by OR-Tools in 2.4s</span>
      </div>
    </MockupFrame>
  );
}

function FinanceMockup() {
  const rows = [
    { label: "Tuition Fees",   amount: "₹42,80,000", pct: 86, color: "bg-emerald-500" },
    { label: "Hostel Fees",    amount: "₹11,25,000", pct: 64, color: "bg-teal-500" },
    { label: "Exam Fees",      amount: "₹3,40,000",  pct: 91, color: "bg-violet-500" },
    { label: "Transport Fees", amount: "₹2,10,000",  pct: 48, color: "bg-purple-400" },
  ];
  return (
    <MockupFrame title="aura.edu/finance">
      <div className="flex items-baseline justify-between mb-4">
        <div>
          <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Collected this term</p>
          <p className="text-2xl font-black text-white">₹59,55,000</p>
        </div>
        <Chip label="Razorpay · Live" cls="bg-blue-500/15 text-blue-400 border border-blue-500/25" />
      </div>
      <div className="space-y-3">
        {rows.map(row => (
          <div key={row.label}>
            <div className="flex justify-between text-[11px] mb-1">
              <span className="text-slate-400 font-semibold">{row.label}</span>
              <span className="text-slate-300 font-bold">{row.amount}</span>
            </div>
            <div className="h-1.5 rounded-full bg-slate-800 overflow-hidden">
              <div className={`h-full rounded-full ${row.color}`} style={{ width: `${row.pct}%` }} />
            </div>
          </div>
        ))}
      </div>
    </MockupFrame>
  );
}

function RingStat({ pct, label, color }: { pct: number; label: string; color: string }) {
  const r = 26, c = 2 * Math.PI * r;
  return (
    <div className="flex flex-col items-center gap-1">
      <svg width="68" height="68" viewBox="0 0 68 68" aria-hidden="true">
        <circle cx="34" cy="34" r={r} fill="none" stroke="#1E293B" strokeWidth="7" />
        <circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="7" strokeLinecap="round"
          strokeDasharray={`${(pct / 100) * c} ${c}`} transform="rotate(-90 34 34)" />
        <text x="34" y="38" textAnchor="middle" fill="#fff" fontSize="13" fontWeight="800">{pct}%</text>
      </svg>
      <span className="text-[10px] text-slate-500 font-semibold">{label}</span>
    </div>
  );
}

function StudentMockup() {
  return (
    <MockupFrame title="aura.edu/student-portal">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-9 h-9 rounded-full bg-violet-600 flex items-center justify-center text-white text-xs font-black">AK</div>
        <div>
          <p className="text-xs font-bold text-white">Anita Kumar</p>
          <p className="text-[10px] text-slate-500">II B.Sc CS · Roll 22CS041</p>
        </div>
        <Chip label="Fees: Paid ✓" cls="ml-auto bg-emerald-500/15 text-emerald-400 border border-emerald-500/25" />
      </div>
      <div className="flex justify-around mb-4">
        <RingStat pct={92} label="Attendance" color="#8B5CF6" />
        <RingStat pct={84} label="CIA Avg" color="#10B981" />
        <RingStat pct={71} label="Syllabus" color="#F59E0B" />
      </div>
      <div className="rounded-lg bg-slate-800/70 px-3 py-2 flex justify-between items-center">
        <span className="text-[11px] text-slate-400 font-semibold">Semester results</span>
        <span className="text-[11px] font-black text-emerald-400">GPA 8.6</span>
      </div>
    </MockupFrame>
  );
}

function StaffMockup() {
  const today = [
    { time: "09:00", cls: "CS101 · II Year A", color: "border-violet-500" },
    { time: "11:00", cls: "CS233 · III Year B", color: "border-cyan-500" },
    { time: "14:00", cls: "LAB-2 · II Year A", color: "border-emerald-500" },
  ];
  return (
    <MockupFrame title="aura.edu/staff-portal">
      <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider mb-2">Today&apos;s schedule</p>
      <div className="space-y-2 mb-4">
        {today.map(t => (
          <div key={t.time} className={`flex items-center gap-3 rounded-lg bg-slate-800/70 px-3 py-2 border-l-2 ${t.color}`}>
            <span className="text-[11px] font-black text-white">{t.time}</span>
            <span className="text-[11px] text-slate-400 font-semibold">{t.cls}</span>
          </div>
        ))}
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div className="rounded-lg bg-slate-800/70 px-3 py-2.5">
          <p className="text-[10px] text-slate-500 font-semibold">Casual leave left</p>
          <p className="text-sm font-black text-white">8 days</p>
        </div>
        <div className="rounded-lg bg-slate-800/70 px-3 py-2.5">
          <p className="text-[10px] text-slate-500 font-semibold">May payslip</p>
          <p className="text-sm font-black text-emerald-400">Ready ↓</p>
        </div>
      </div>
    </MockupFrame>
  );
}

function AttendanceMockup() {
  const sessions = [
    { name: "CS101 · 09:00", marked: "58/62", ok: true },
    { name: "MA204 · 10:00", marked: "60/61", ok: true },
    { name: "PH110 · 11:00", marked: "44/59", ok: false },
  ];
  return (
    <MockupFrame title="aura.edu/attendance">
      <div className="flex items-center gap-2 mb-4 rounded-lg bg-violet-500/10 border border-violet-500/25 px-3 py-2.5">
        <Nfc size={16} className="text-violet-400" />
        <span className="text-[11px] font-bold text-violet-300">NFC reader connected</span>
        <span className="ml-auto flex items-center gap-1 text-[10px] text-emerald-400 font-bold">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" /> LIVE
        </span>
      </div>
      <div className="space-y-2">
        {sessions.map(s => (
          <div key={s.name} className="flex items-center justify-between rounded-lg bg-slate-800/70 px-3 py-2.5">
            <span className="text-[11px] text-slate-300 font-semibold">{s.name}</span>
            <Chip label={s.marked}
              cls={s.ok
                ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/25"
                : "bg-rose-500/15 text-rose-400 border border-rose-500/25"} />
          </div>
        ))}
      </div>
    </MockupFrame>
  );
}

function CiaMockup() {
  const rows = [
    { comp: "CIA Test 1", max: 20, got: 17 },
    { comp: "CIA Test 2", max: 20, got: 18 },
    { comp: "Assignment", max: 10, got: 9 },
  ];
  return (
    <MockupFrame title="aura.edu/cia-ledger">
      <table className="w-full text-[11px]">
        <thead>
          <tr className="text-slate-500 uppercase text-[9px] tracking-wider">
            <th className="text-left pb-2 font-bold">Component</th>
            <th className="text-right pb-2 font-bold">Max</th>
            <th className="text-right pb-2 font-bold">Scored</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(r => (
            <tr key={r.comp} className="border-t border-slate-800">
              <td className="py-2 text-slate-300 font-semibold">{r.comp}</td>
              <td className="py-2 text-right text-slate-500">{r.max}</td>
              <td className="py-2 text-right text-white font-black">{r.got}</td>
            </tr>
          ))}
          <tr className="border-t border-slate-700">
            <td className="py-2 font-black text-violet-300">Internal (formula)</td>
            <td className="py-2 text-right text-slate-500">50</td>
            <td className="py-2 text-right font-black text-emerald-400">44</td>
          </tr>
        </tbody>
      </table>
      <p className="mt-2 text-[10px] text-slate-500 font-mono">= (CIA1 + CIA2) × 0.5 + Assignment × 2.5</p>
    </MockupFrame>
  );
}

function AccreditationMockup() {
  const reports = [
    { name: "NAAC SSR — Criterion 2", status: "Ready" },
    { name: "NIRF Ranking Extract",   status: "Ready" },
    { name: "NBA SAR — CSE",          status: "Ready" },
  ];
  return (
    <MockupFrame title="aura.edu/reports">
      <div className="space-y-2 mb-4">
        {reports.map(r => (
          <div key={r.name} className="flex items-center justify-between rounded-lg bg-slate-800/70 px-3 py-2.5">
            <span className="text-[11px] text-slate-300 font-semibold">{r.name}</span>
            <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-400">
              <CheckCircle2 size={11} /> {r.status}
            </span>
          </div>
        ))}
      </div>
      <button type="button" tabIndex={-1}
        className="w-full py-2 rounded-lg bg-violet-600 text-white text-[11px] font-black pointer-events-none">
        Export Evidence Bundle (PDF) →
      </button>
    </MockupFrame>
  );
}

function AdmissionsMockup() {
  const funnel = [
    { stage: "Enquiries",    count: "1,240", pct: 100, color: "bg-cyan-500" },
    { stage: "Applications", count: "780",   pct: 63,  color: "bg-sky-500" },
    { stage: "Merit-listed", count: "560",   pct: 45,  color: "bg-blue-500" },
    { stage: "Admitted",     count: "420",   pct: 34,  color: "bg-violet-500" },
  ];
  return (
    <MockupFrame title="aura.edu/admissions/crm">
      <div className="flex items-baseline justify-between mb-4">
        <div>
          <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Conversion rate</p>
          <p className="text-2xl font-black text-white">33.9%</p>
        </div>
        <Chip label="2026 intake · Live" cls="bg-cyan-500/15 text-cyan-400 border border-cyan-500/25" />
      </div>
      <div className="space-y-3">
        {funnel.map(f => (
          <div key={f.stage}>
            <div className="flex justify-between text-[11px] mb-1">
              <span className="text-slate-400 font-semibold">{f.stage}</span>
              <span className="text-slate-300 font-bold">{f.count}</span>
            </div>
            <div className="h-1.5 rounded-full bg-slate-800 overflow-hidden">
              <div className={`h-full rounded-full ${f.color}`} style={{ width: `${f.pct}%` }} />
            </div>
          </div>
        ))}
      </div>
    </MockupFrame>
  );
}

function PlacementsMockup() {
  const offers = [
    { co: "Zoho",     ctc: "₹9.0 LPA", n: "12 offers" },
    { co: "TCS",      ctc: "₹7.0 LPA", n: "34 offers" },
    { co: "Infosys",  ctc: "₹6.5 LPA", n: "28 offers" },
  ];
  return (
    <MockupFrame title="aura.edu/placements">
      <div className="grid grid-cols-3 gap-2.5 mb-4">
        {[
          { label: "Placed", value: "86%" },
          { label: "Highest", value: "₹24L" },
          { label: "Offers", value: "312" },
        ].map(k => (
          <div key={k.label} className="rounded-xl bg-slate-800/70 px-3 py-2.5">
            <p className="text-[9px] text-slate-500 uppercase tracking-wider font-bold leading-tight">{k.label}</p>
            <p className="text-sm font-black text-white mt-1 leading-tight">{k.value}</p>
          </div>
        ))}
      </div>
      <div className="space-y-2">
        {offers.map(o => (
          <div key={o.co} className="flex items-center justify-between rounded-lg bg-slate-800/70 px-3 py-2.5">
            <span className="text-[11px] text-slate-300 font-semibold">{o.co}</span>
            <span className="text-[10px] text-slate-500 font-semibold">{o.n}</span>
            <Chip label={o.ctc} cls="bg-indigo-500/15 text-indigo-300 border border-indigo-500/25" />
          </div>
        ))}
      </div>
    </MockupFrame>
  );
}

function MobileMockup() {
  return (
    <div className="flex justify-center">
      <div className="w-52 rounded-[2rem] border-4 border-slate-700 bg-slate-900 shadow-2xl shadow-black/50 overflow-hidden">
        <div className="h-5 bg-slate-800 flex items-center justify-center">
          <div className="w-14 h-1.5 rounded-full bg-slate-700" />
        </div>
        <div className="p-3 space-y-2">
          <div className="flex items-center gap-2 rounded-xl bg-violet-500/15 border border-violet-500/25 px-3 py-2.5">
            <Nfc size={14} className="text-violet-400" />
            <span className="text-[10px] font-bold text-violet-300">Tap card to mark attendance</span>
          </div>
          <div className="flex items-center gap-2 rounded-xl bg-slate-800 px-3 py-2.5">
            <Bell size={13} className="text-amber-400" />
            <span className="text-[10px] text-slate-300 font-semibold">CIA-2 marks published</span>
          </div>
          <div className="flex items-center gap-2 rounded-xl bg-slate-800 px-3 py-2.5">
            <Video size={13} className="text-cyan-400" />
            <span className="text-[10px] text-slate-300 font-semibold">Gate camera · Block A live</span>
          </div>
          <div className="flex items-center gap-2 rounded-xl bg-slate-800 px-3 py-2.5">
            <Wifi size={13} className="text-emerald-400" />
            <span className="text-[10px] text-slate-300 font-semibold">Synced · 2 min ago</span>
          </div>
        </div>
      </div>
    </div>
  );
}

const MOCKUPS: Record<MockupVariant, () => React.ReactElement> = {
  timetable: TimetableMockup,
  finance: FinanceMockup,
  student: StudentMockup,
  staff: StaffMockup,
  attendance: AttendanceMockup,
  cia: CiaMockup,
  accreditation: AccreditationMockup,
  mobile: MobileMockup,
  admissions: AdmissionsMockup,
  placements: PlacementsMockup,
};

/* ── Per-panel theme driven by index % 3 ───────────────────────────────── */

type ThemeKey = "light" | "dark" | "purple";

const PANEL_THEMES: Record<ThemeKey, {
  bg: string;
  bgNumber: string;
  labelText: string;
  labelLine: string;
  labelCounter: string;
  heading: string;
  desc: string;
  bullet: string;
  bulletIcon: string;
  btn: string;
  badge: string;
}> = {
  light: {
    bg:           "bg-white",
    bgNumber:     "text-slate-900/[0.04]",
    labelText:    "text-violet-500",
    labelLine:    "bg-slate-200",
    labelCounter: "text-slate-400",
    heading:      "text-slate-900",
    desc:         "text-slate-600",
    bullet:       "text-slate-700",
    bulletIcon:   "text-emerald-600",
    btn:          "text-violet-600 hover:text-violet-500",
    badge:        "bg-amber-100 border border-amber-300 text-amber-700",
  },
  dark: {
    bg:           "bg-slate-950",
    bgNumber:     "text-white/[0.04]",
    labelText:    "text-violet-400",
    labelLine:    "bg-slate-700",
    labelCounter: "text-slate-600",
    heading:      "text-white",
    desc:         "text-slate-400",
    bullet:       "text-slate-300",
    bulletIcon:   "text-emerald-400",
    btn:          "text-violet-400 hover:text-violet-300",
    badge:        "bg-amber-500/15 border border-amber-500/30 text-amber-400",
  },
  purple: {
    bg:           "bg-gradient-to-br from-violet-950 via-purple-950 to-violet-900",
    bgNumber:     "text-white/[0.04]",
    labelText:    "text-violet-300",
    labelLine:    "bg-violet-700",
    labelCounter: "text-violet-700",
    heading:      "text-white",
    desc:         "text-violet-200",
    bullet:       "text-violet-100",
    bulletIcon:   "text-emerald-400",
    btn:          "text-violet-200 hover:text-white",
    badge:        "bg-amber-400/15 border border-amber-400/30 text-amber-300",
  },
};

/* ── Panel ─────────────────────────────────────────────────────────────── */

export function FeaturePanel({
  feature,
  index,
  total,
}: {
  feature: FeaturePanelData;
  index: number;
  total: number;
}) {
  const { scrollToId } = useLenis();
  const Mockup = MOCKUPS[feature.variant];
  const number = String(index + 1).padStart(2, "0");
  const totalStr = String(total).padStart(2, "0");

  const themeKey: ThemeKey = index % 3 === 0 ? "light" : index % 3 === 1 ? "dark" : "purple";
  const t = PANEL_THEMES[themeKey];

  return (
    <div
      className={`feature-panel relative w-full md:w-screen md:h-screen shrink-0 flex items-center overflow-hidden py-16 md:py-0 transition-colors duration-500 ${t.bg}`}
    >
      {/* Purple mode: atmospheric glow orbs */}
      {themeKey === "purple" && (
        <div className="absolute inset-0 pointer-events-none" aria-hidden="true">
          <div className="absolute top-1/4 -left-24 w-96 h-96 bg-violet-600/20 rounded-full blur-3xl" />
          <div className="absolute bottom-1/4 -right-24 w-96 h-96 bg-purple-600/20 rounded-full blur-3xl" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-fuchsia-600/8 rounded-full blur-3xl" />
        </div>
      )}

      {/* "Features of AURA CAMPUS™" persistent section label */}
      <div className="absolute top-0 left-0 right-0 flex items-center gap-3 px-4 sm:px-10 pt-5 z-20">
        <div className={`w-1.5 h-1.5 rounded-full bg-violet-500 shrink-0`} />
        <span className={`text-[10px] font-black uppercase tracking-widest ${t.labelText} opacity-80`}>
          Features of AURA CAMPUS™
        </span>
        <div className={`flex-1 h-px ${t.labelLine} opacity-40`} />
        <span className={`text-[10px] font-bold tabular-nums ${t.labelCounter} opacity-70`}>
          {number} / {totalStr}
        </span>
      </div>

      {/* Large faded background number */}
      <span aria-hidden="true"
        className={`absolute top-8 left-4 sm:left-10 text-[9rem] sm:text-[13rem] font-black leading-none ${t.bgNumber} select-none pointer-events-none`}>
        {number}
      </span>

      <div className="panel-inner relative z-10 max-w-6xl mx-auto w-full grid md:grid-cols-2 gap-10 md:gap-16 items-center px-4 sm:px-8">
        <div>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-2xl flex items-center justify-center shadow-lg"
              style={{ backgroundImage: feature.gradient }}>
              <feature.icon size={22} className="text-white" />
            </div>
            {feature.comingSoon && (
              <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider ${t.badge}`}>
                Coming Soon · Phase 8
              </span>
            )}
          </div>

          <h3 className={`text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight mb-4 ${t.heading}`}>
            {feature.title}
          </h3>
          <p className={`text-base sm:text-lg leading-relaxed mb-6 ${t.desc}`}>
            {feature.desc}
          </p>

          <ul className="space-y-2.5 mb-7">
            {feature.bullets.map(b => (
              <li key={b} className={`flex items-start gap-2.5 text-sm ${t.bullet}`}>
                <CheckCircle2 size={16} className={`${t.bulletIcon} mt-0.5 shrink-0`} />
                <span>{b}</span>
              </li>
            ))}
          </ul>

          <button type="button" onClick={() => scrollToId("contact")}
            className={`inline-flex items-center gap-1.5 text-sm font-bold transition-colors group ${t.btn}`}>
            Learn more
            <ArrowRight size={15} className="group-hover:translate-x-0.5 transition-transform" />
          </button>
        </div>

        <div className="w-full max-w-md mx-auto md:max-w-none">
          <Mockup />
        </div>
      </div>
    </div>
  );
}
